Repository TonyGermaneri/canvas-datagrid, pull requests merged in 2020-09, with the labels that each got.

#288 Paste event improvements
  lib/docs.js
  lib/events.js
  lib/intf.js
  test/tests.js
Labels: enhancement

#291 Fill paste values in multiple selected cells
  lib/events.js
Labels: enhancement

#299 Type to enter text
  .babelrc
  .github/workflows/manual-docs-publish.yml
  .github/workflows/manual-npm-publish.yml
  .github/workflows/release.yml
  README.md
  lib/contextMenu.js
  lib/dom.js
  lib/events.js
  package-lock.json
  package.json
  test/tests.js
  webpack.config.js
Labels: enhancement

#303 Add autoResizeRows attribute for optionally resizing rows to fit wrapped text
  lib/defaults.js
  lib/docs.js
  lib/draw.js
  test/tests.js
Labels: enhancement

#305 Fix webcomponent data and schema attributes
  lib/component.js
Labels: bug

#304 Make distinction between "enter" and "edit" modes
  lib/docs.js
  lib/dom.js
  lib/events.js
Labels: bug, enhancement

#308 Fix bug that causes current selections to be overwritten when cell on only 1 row is selected
  lib/events.js
Labels: bug

#309 Fix grid not resizing when `autoResizeRows` is enabled
  lib/draw.js
Labels: bug
